//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accommodation()
        {
            this.AccFeedbacks = new HashSet<AccFeedback>();
        }
    
        public int AccommodationID { get; set; }
        public string Name { get; set; }
        public int AccCategoryID { get; set; }
        public int CityID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
    
        public virtual AccCategory AccCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccFeedback> AccFeedbacks { get; set; }
        public virtual City City { get; set; }
    }
}
