//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityInfoByCategory
    {
        public int CityID { get; set; }
        public int CityCategoryID { get; set; }
        public string Info { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual City City { get; set; }
        public virtual CityCategory CityCategory { get; set; }
        public virtual User User { get; set; }
    }
}
