//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeedbackID { get; set; }
        public int CommentID { get; set; }
        public int RatingID { get; set; }
        public int UserID { get; set; }
        public int TransportationProviderID { get; set; }
    
        public virtual User User { get; set; }
    }
}
