//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TransportaitonProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportaitonProvider()
        {
            this.Transportaitons = new HashSet<Transportaiton>();
            this.TransportationFeedbacks = new HashSet<TransportationFeedback>();
            this.TransportatitonComments = new HashSet<TransportatitonComment>();
            this.TransportatitonRatings = new HashSet<TransportatitonRating>();
        }
        public int TransportationProviderID { get; set; }
        [Required(ErrorMessage = "You must enter name of transportation provider")]
        public string TransportationProviderName { get; set; }
        public int CountryID { get; set; }
        [Required(ErrorMessage = "You must enter street name of transportation provider")]
        public string StreetName { get; set; }
        [Required(ErrorMessage = "You must enter street number of transportation provider")]
        public string StreetNumber { get; set; }
        [Required(ErrorMessage = "Phone Number is needed.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\+\s?)?((?<!\+.*)\(\+?\d+([\s\-\.]?\d+)?\)|\d+)([\s\-\.]?(\(\d+([\s\-\.]?\d+)?\)|\d+))*(\s?(x|ext\.?)\s?\d+)?$", ErrorMessage = "The PhoneNumber field is not a valid phone number")]
        public string Phone { get; set; }

        public int TransportaitonTypeID { get; set; }
        public int CityID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportaiton> Transportaitons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationFeedback> TransportationFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportatitonComment> TransportatitonComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportatitonRating> TransportatitonRatings { get; set; }
        public virtual TransportaitonType TransportaitonType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
