//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportaiton
    {
        public int TransportaitonID { get; set; }
        public int CityFromID { get; set; }
        public int CityToID { get; set; }
        public int TransportaitonProviderID { get; set; }
        public int TransportaionTypeID { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual TransportaitonProvider TransportaitonProvider { get; set; }
        public virtual TransportaitonType TransportaitonType { get; set; }
    }
}
