//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportatitonRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportatitonRating()
        {
            this.TransportationFeedbacks = new HashSet<TransportationFeedback>();
        }
    
        public int RatingID { get; set; }
        public int UserID { get; set; }
        public int StarRating { get; set; }
        public System.DateTime Date { get; set; }
        public int TrasportationProviderID { get; set; }
    
        public virtual TransportaitonProvider TransportaitonProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationFeedback> TransportationFeedbacks { get; set; }
        public virtual User User { get; set; }
    }
}
