//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationFeedback
    {
        public int FeedBackID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public Nullable<int> RatingID { get; set; }
        public int UserID { get; set; }
        public int TransportationProviderID { get; set; }
    
        public virtual TransportaitonProvider TransportaitonProvider { get; set; }
        public virtual TransportatitonComment TransportatitonComment { get; set; }
        public virtual TransportatitonRating TransportatitonRating { get; set; }
        public virtual User User { get; set; }
    }
}
